package lcode;

/**
 * 389. Find the Difference
 * @author smeng
 *
 */

//Given two strings s and t which consist of only lowercase letters.
//
//String t is generated by random shuffling string s and then add one more letter at a random position.
//
//Find the letter that was added in t.

public class FindtheDifference {
	public static char findTheDifference(String s, String t) {
		char d = 0;
		for(char c: (s+t).toCharArray()) {
			d ^= c;
		}
		return d;
	}
	public static void main(String[] args) {
		// TODO Auto-generated method stub
		String s = "wedaefcw";
		String t = "wedsaefcw";
		System.out.println(findTheDifference(s,t));
	}

}
